[package]
name = "birthday_paradox"
version = "0.1.0"
authors = ["Joseph Lyons <josephtlyons@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.7"
rand = "0.7.0"
